version: '3.3'
services:
    watchtower:
        container_name: watchtower
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        restart: unless-stopped
        environment:
            - TZ=Europe/Berlin
            - WATCHTOWER_INCLUDE_RESTARTING=true
            - WATCHTOWER_POLL_INTERVAL=300
            - WATCHTOWER_CLEANUP=true
        image: containrrr/watchtower
